### ISSUE TITLE
future compatibility problem in dependencies

### ISSUE THREAD

**Issue by hdhoang** [uberblah/rust-graphics-experiments#1]
Hi, due to rust-lang/rust#49799, one of your dependencies will no longer build. From looking at your Cargo.toml, we recommend you upgrade to
nalgebra version 0.14 or later. Thanks for your attention!

**Comment by uberblah** [comment]
Thanks for the reminder! Will update. Personal project, not in active use.

**Comment by uberblah** [comment]
Updated! See c4db1481ce9797076b7b50f197bd4612239ed3fe
